apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-capstone
  template:
    metadata:
      labels:
        app: my-capstone
    spec:
      containers:
      - name: my-capstone
        image: kevmare/capstone_project:ver-${CIRCLE_WORKFLOW_ID:0:5}:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
    #  maxSurge: 50%
      maxSurge: 1
      maxUnavailable: 1
---
apiVersion: v1
kind: Service
metadata:
  name: my-capstone
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 30000
  selector:
    app: my-capstone
  type: LoadBalancer