apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-capstone
  labels:
    app: my-capstone
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-capstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-capstone
    spec:
      containers:
        - image: kevmare/capstone_project:ver-9672a
          imagePullPolicy: Always
          name: capstone_project
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-capstone
  labels:
    app: my-capstone
spec:
  type: LoadBalancer
  selector:
    app: my-capstone
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP