version: 2.1

jobs:
  test-build:
    docker:
      # Use the same Docker base as the project
      - image: python:3.7.3-stretch

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate 
            make lint 
  build-docker:
    docker:
      - image: python:3.7
    steps:
      - checkout

      # Build Docker image
      - run:
          name: Build Docker image
          command: |
            docker --version
            docker build --tag=$DOCKER_IMAGE_NAME .
            docker image ls

      # Authenticate with Docker Hub
      - run:
          name: Login to Docker Hub
          command: |
            echo "Docker ID and Image: $DOCKER_IMAGE_NAME"
            docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"

      # Push Docker image to Docker Hub
      - run:
          name: Push image to Docker Hub
          command: |
            echo "Docker ID and Image: $DOCKER_IMAGE_NAME"
            
            docker tag $DOCKER_IMAGE_NAME $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME:$CIRCLE_WORKFLOW_ID:0:7
            docker push $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME:$CIRCLE_WORKFLOW_ID 
workflows:
  default:
    jobs:
      - test-build
      - build-docker:
          requires:
            - test-build